language: python
python:
  - "2.6"
  - "2.7"
env:
  - DJANGO=1.3 DB=postgres
  - DJANGO=1.3 DB=mysql
  - DJANGO=1.4 DB=postgres
  - DJANGO=1.4 DB=mysql
install: "pip install --use-mirrors"
script: python manage.py test skwissh