language: python
python:
  - "2.5"
  - "2.6"
  - "2.7"
  - "3.2"
env:
  - DJANGO=1.4
  - DJANGO=1.4.1
install:
  - pip install -q Django==$DJANGO
  - pip install -q . --use-mirrors
script: python testproject/manage.py test skwissh